### ISSUE TITLE
cntc_gethertzcontact.m - Return value does not correspond to variable name

### ISSUE THREAD

**Issue by JPu96** [eve70a/CONTACT#7]
Hello, 
I've found a bug in matlab_intfc script cntc_gethertzcontact.m. The return value name (named 'rvalues') doesn't correspond to actual variable name with values from CONTACT library (named only 'values' - on line 45).

Thank you for solving!
Jan

**Comment by eve70a** [comment]
Solved. Thanks for reporting.
